create table if not exists public.vault_notes (
  id bigint generated by default as identity primary key,
  owner_id uuid,
  title text not null,
  content text not null,
  created_at timestamptz not null default now()
);

alter table public.vault_notes enable row level security;

grant select on table public.vault_notes to service_role;

revoke all on table public.vault_notes from anon, authenticated;